---
title: "Incomplete Neutralization"
author: Timo Roettger
date: 2026-06-06
format:
  html:
    embed-resources: true
editor: visual
---

```{r}
#| include: FALSE

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

```

```{r}
#| label: setup
#| include: FALSE

# read in libraries
if (!require("pacman")) install.packages("pacman")
pacman::p_load(viridis, brms, tidyverse, here, knitr, kableExtra, broom, patchwork, plotly, htmlwidgets, webshot2, ggrepel, gghighlight)

```

```{r}
#| label: data_wrangling

# load in data 2026/06/01
xdata <- read_csv(here::here("Derived_Data", "Estimates.csv")) |> 
  # calc precision
  mutate(precision = 1/(Est.Error^2)) |> 
  # add fill names
  mutate(long_name = fct_recode(short_name,
                    "Fuchs '05"  = "F05",
                    "Grawunder '14"    = "G14",
                    "Roettger et al. '14(1)"    = "Rea14_1",
                    "Roettger et al. '14(2)"  = "Rea14_2",
                    "Roettger & Baer-Henney '19(1)"  = "B_1",
                    "Roettger & Baer-Henney '19(2)"    = "B_2",
                    "Mitleb '81"    = "M81",
                    "Fourakis & Iverson '84"  = "FI84",
                    "Port & O'Dell '85"    = "PO85",
                    "Port & Crawford '89"    = "PC89",
                    "Greisbach '01"  = "G01",
                    "Piroth & Janker '04"    = "PJ04",
                    "Charles-Luce '85"    = "C85",
                    "Smith et al. '09"    = "Sea09"),
         short_new_name = fct_recode(short_name,
                    "F-2005"  = "F05",
                    "G-2014"    = "G14",
                    "R-2014(1)"    = "Rea14_1",
                    "R-2014(2)"  = "Rea14_2",
                    "R&B-2019(1)"  = "B_1",
                    "R&B-2019(2)"    = "B_2",
                    "M-1981"    = "M81",
                    "F&I-1984"  = "FI84",
                    "P&D-1985"    = "PO85",
                    "P&C-1989"    = "PC89",
                    "G-2001"  = "G01",
                    "P&J-2004"    = "PJ04",
                    "CL-1985"    = "C85",
                    "S-2009"    = "Sea09"))

# meta-analytical estimates
model <- readRDS(here::here("Models", "meta_analysis.rds"))
ma_est <- fixef(model)[1]
ma_lb <- fixef(model)[3]
ma_ub <- fixef(model)[4]
```


```{r}

# Same ordering ggplot uses internally for reorder(long_name, prop*100)
y_levels <- levels(reorder(xdata$long_name, xdata$prop))
xdata$y_num  <- match(xdata$long_name, y_levels)   # numeric y-position of each row

# Identify the three points with the largest x-value (prop)
top3 <- xdata |> 
  arrange(desc(prop)) |> 
  slice(1:3)

# Choose a location for the converging label 
label_x <- 25
label_y <- median(top3$y_num) - 2   # a bit below the cluster of top points


icphs_plot <- 
  xdata |> 
  ggplot(aes(x = prop*100, 
             y = reorder(short_new_name, prop*100),
             size = precision)) +
  # meta-analysis
  geom_rect(aes(xmin = ma_lb*100,
               xmax = ma_ub*100,
               ymin = -Inf,
               ymax = Inf),
               fill = "#9E69CA",
               alpha = .2
               ) +
  geom_segment(x = ma_est*100,
               xend = ma_est*100,
               y = -Inf,
               yend = Inf,
               lwd = 1,
               color = "white") +
  # geom_point(data = xdata |> 
  #              filter(short_new_name %in% c("F&I-1984",
  #                                           "P&J-2004")),
  #            pch = 21,
  #            color = "white",
  #            fill = "pink") +
  # geom_point(data = xdata |> 
  #              filter(short_new_name != "F&I-1984",
  #                     short_new_name != "P&J-2004"),
  #            pch = 21,
  #            color = "white",
  #            fill = "#6D26A6") +
  geom_point(pch = 21,
             color = "white",
             fill = "#6D26A6") +
  scale_size(range = c(3, 8)) +
  geom_vline(xintercept = 0,
             lty = "dashed") +
  # arrows converging on the label, one per top-3 point
  ## F05  
  annotate("curve",
           x = label_x, xend = top3$prop[1]*100,
           y = label_y, yend = top3$y_num[1] - 0.5,
           linewidth = 0.1, color = "black",
           curvature = 0.3,
           arrow = arrow(length = unit(0.05, "inches"), type = "closed")) +
  ## M81  
  annotate("curve",
           x = label_x, xend = top3$prop[2]*100 + 1,
           y = label_y, yend = top3$y_num[2],
           linewidth = 0.1, color = "black",
           curvature = 0.3,
           arrow = arrow(length = unit(0.05, "inches"), type = "closed")) +
  ## G14  
  annotate("curve",
           x = label_x, xend = top3$prop[3]*100 + 1.5,
           y = label_y, yend = top3$y_num[3],
           linewidth = 0.1, color = "black",
           curvature = 0.3,
           arrow = arrow(length = unit(0.05, "inches"), type = "closed")) +
  # text
  annotate("label",
           x = label_x, y = label_y,
           label = "incomplete\nneutralization?",
           family = "times",
           border.colour = "white",
           size = 4,
           hjust = 0.5, vjust = 0.5) +
  scale_x_continuous(limits = c(-5,35),
                     breaks = seq(-5,35,5),
                     labels = seq(-5,35,5)) +
  #scale_y_discrete(labels = scales::label_wrap(15)) +
  labs(title = "Effect magnitudes of meta-analysis\n(Nicenboim et al. 2018)",
       subtitle = "projected onto % vowel duration",
       x = "\nvowel duration difference in %",
       y = "") +
  theme_minimal() +
  theme(legend.position = "none",
        text = element_text(family = "times"),
        axis.text.y = element_text(size = 8))

# save wide format
ggsave(filename = here::here("Plots","icphs_plot.png"), 
       plot = icphs_plot,
       width = 180, 
       height = 120,
       units = "mm", 
       bg = "transparent",
       dpi = 300)

# save long format
ggsave(filename = here::here("Plots","icphs_plot_long.png"), 
       plot = icphs_plot,
       width = 100, 
       height = 100,
       units = "mm", 
       bg = "transparent",
       dpi = 300)

```
